
import React, { useState } from 'react';
import DownloadIcon from './icons/DownloadIcon';
import ExpandIcon from './icons/ExpandIcon';
import Modal from './Modal';

interface GeneratedImageProps {
  imageUrl: string | null;
  text: string | null;
}

const GeneratedImage: React.FC<GeneratedImageProps> = ({ imageUrl, text }) => {
  const [isModalOpen, setIsModalOpen] = useState(false);

  if (!imageUrl) {
    return null;
  }

  const handleDownload = () => {
    const link = document.createElement('a');
    link.href = imageUrl;
    link.download = 'yisan-ai-try-on.png';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };
  
  return (
    <div className="w-full max-w-2xl mx-auto p-6 mt-4 space-y-4 bg-white/70 backdrop-blur-sm rounded-2xl shadow-lg border border-slate-200/50">
      <h2 className="text-2xl font-semibold text-center text-slate-700">生成效果</h2>
      <div className="relative group aspect-square">
        <img src={imageUrl} alt="Generated by AI" className="w-full h-full object-contain rounded-md" />
        <div className="absolute inset-0 flex items-center justify-center bg-black bg-opacity-0 group-hover:bg-opacity-50 transition-opacity duration-300 rounded-md">
          <div className="flex space-x-4 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
             <button
              onClick={() => setIsModalOpen(true)}
              className="py-2 px-4 text-white bg-black/50 rounded-full hover:bg-black/70 transition-all transform hover:scale-110 flex items-center text-sm"
              title="查看大图"
            >
              <ExpandIcon className="w-5 h-5 mr-2" /> 查看大图
            </button>
            <button
              onClick={handleDownload}
              className="py-2 px-4 text-white bg-black/50 rounded-full hover:bg-black/70 transition-all transform hover:scale-110 flex items-center text-sm"
              title="保存图片"
            >
              <DownloadIcon className="w-5 h-5 mr-2" /> 保存图片
            </button>
          </div>
        </div>
      </div>
      {text && (
        <div className="p-4 bg-indigo-50 rounded-lg">
          <p className="text-sm text-slate-600"><span className="font-semibold text-indigo-700">AI说:</span> {text}</p>
        </div>
      )}
      <Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} imageUrl={imageUrl} />
    </div>
  );
};

export default GeneratedImage;
